name: Sync Doppler Secrets to Netlify

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Doppler CLI
        run: curl -Ls https://dl.doppler.com/install.sh | sh

      - name: Export Doppler Secrets
        run: |
          doppler secrets download \
            --no-file \
            --format json \
            --token ${{ secrets.GH_TOKEN }} \
            --project your-project \
            --config prod > doppler-secrets.json

      - name: Upload to Netlify
        uses: nwtgck/actions-netlify-env@v1
        with:
          netlify_auth_token: ${{ secrets.NETLIFY_TOKEN }}
          netlify_site_id: ${{ secrets.NETLIFY_SITE_ID }}
          env_file_path: doppler-secrets.json
          format: json
